import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {createPrivateKey,sign} from 'node:crypto';
const API='https://api.appstoreconnect.apple.com',tmp=process.env.RUNNER_TEMP,mode=process.argv[2]||'prepare',statePath=path.join(tmp,'redxai-adhoc-state.json');
function jwt(){const raw=fs.readFileSync(path.join(tmp,'asc',`AuthKey_${process.env.ASC_KEY_ID}.p8`),'utf8'),key=createPrivateKey(raw),now=Math.floor(Date.now()/1000),enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url'),u=`${enc({alg:'ES256',kid:process.env.ASC_KEY_ID,typ:'JWT'})}.${enc({iss:process.env.ASC_ISSUER_ID,iat:now-5,exp:now+115,aud:'appstoreconnect-v1'})}`;return `${u}.${sign('sha256',Buffer.from(u),{key,dsaEncoding:'ieee-p1363'}).toString('base64url')}`}
async function api(method,route,body){const r=await fetch(API+route,{method,headers:{Authorization:`Bearer ${jwt()}`,Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok){throw new Error(`Apple API ${method} ${route} HTTP ${r.status}: ${(await r.text()).slice(0,400)}`)}return r.status===204?null:r.json()}
const env=(k,v)=>fs.appendFileSync(process.env.GITHUB_ENV,`${k}=${v}\n`);
async function prepare(){const udid=process.argv[3];if(!udid)throw new Error('Missing device UDID');let devices=await api('GET',`/v1/devices?filter%5Budid%5D=${encodeURIComponent(udid)}&limit=5`);let device=devices.data?.[0];if(!device)device=(await api('POST','/v1/devices',{data:{type:'devices',attributes:{name:'Red-XAI Test iPhone',platform:'IOS',udid}}})).data;
const dir=path.join(tmp,'signing');fs.mkdirSync(dir,{recursive:true,mode:0o700});const keyPath=path.join(dir,'distribution.key'),csrPath=path.join(dir,'distribution.csr');execFileSync('openssl',['genrsa','-out',keyPath,'2048']);execFileSync('openssl',['req','-new','-key',keyPath,'-subj','/CN=Red-XAI AdHoc CI','-out',csrPath]);const cert=(await api('POST','/v1/certificates',{data:{type:'certificates',attributes:{certificateType:'IOS_DISTRIBUTION',csrContent:fs.readFileSync(csrPath,'utf8')}}})).data;fs.writeFileSync(path.join(dir,'distribution.cer'),Buffer.from(cert.attributes.certificateContent,'base64'));
const bundleIdentifier=process.env.SELECTED_APP==='database'?'com.redxai.database':'com.redxai.host',bundles=await api('GET',`/v1/bundleIds?filter%5Bidentifier%5D=${encodeURIComponent(bundleIdentifier)}&limit=5`),bundle=bundles.data?.[0];if(!bundle)throw new Error('Bundle ID missing: '+bundleIdentifier);const profileName=`Red-XAI AdHoc ${process.env.SELECTED_APP} ${process.env.GITHUB_RUN_ID}`;const profile=(await api('POST','/v1/profiles',{data:{type:'profiles',attributes:{name:profileName,profileType:'IOS_APP_ADHOC'},relationships:{bundleId:{data:{type:'bundleIds',id:bundle.id}},certificates:{data:[{type:'certificates',id:cert.id}]},devices:{data:[{type:'devices',id:device.id}]}}}})).data;const pd=path.join(os.homedir(),'Library','MobileDevice','Provisioning Profiles');fs.mkdirSync(pd,{recursive:true});fs.writeFileSync(path.join(pd,profile.id+'.mobileprovision'),Buffer.from(profile.attributes.profileContent,'base64'));fs.writeFileSync(statePath,JSON.stringify({certId:cert.id,profileId:profile.id}));env('RX_PROFILE_NAME',profileName);env('RX_BUNDLE_ID',bundleIdentifier);console.log('Ad Hoc profile created for registered device.')}
async function cleanup(){if(!fs.existsSync(statePath))return;const s=JSON.parse(fs.readFileSync(statePath));for(const [t,id] of [['profiles',s.profileId],['certificates',s.certId]])if(id)try{await api('DELETE',`/v1/${t}/${id}`)}catch(e){console.error('cleanup warning '+e.message)}}
try{mode==='prepare'?await prepare():await cleanup()}catch(e){console.error('::error::'+e.message);process.exitCode=1}
